name: meds-py
channels:
    - conda-forge
    - defaults
dependencies:
    - python
    - cartopy       # Geographic plotting toolkit
    - dask          # Parallel processing library
    - dask_jobqueue # Addition 1/24/2024
    - hvplot
    - ipython       # IPython interpreter and tools
    - jupyter       # Jupyter federation architecture
    - jupyterlab
    - matplotlib    # 2D plotting library
    - netcdf4       # Wrapper for netcdf4
    - notebook      # Notebook interface
    - numpy         # N-d array and numerics
    - pandas        # Labeled array library
    - panel
    - plotly
    - regionmask
    - scipy         # Common math/stats/science functions
    - scikit-learn  # Macine learning library
    - seaborn       # Statistical visualizations
    - shapely
    - sparse
    - statsmodels
    - xarray        # N-d labeled array library
    - xesmf